export const SET_EMAIL_SIGN_UP: string = 'SET_EMAIL_SIGN_UP';
export const SET_FIRST_LAST_NAME_SIGN_UP: string = 'SET_FIRST_LAST_NAME_SIGN_UP';
export const SET_COUNTRY_BIRTH_GENDER_SIGN_UP: string = 'SET_COUNTRY_BIRTH_GENDER_SIGN_UP';
export const SET_PASSWORD_SIGN_UP: string = 'SET_PASSWORD_SIGN_UP';
